### ISSUE TITLE
tcpdump error

### ISSUE THREAD

**Issue by knowpage** [cert-ee/cuckoo3#37]
I got this error when I submit the file to the serrver, it returns "Tasks(s) pending" state with a score of 10 but when I click onto it return a page with an "Server Error (500)". 
 ![image](https://user-images.githubusercontent.com/105774467/236153370-2ca47da1-9188-42df-8359-f61df92eccc0.png)
![image](https://user-images.githubusercontent.com/105774467/236153738-5226e7ed-daa2-422f-81b5-b73b0f607348.png)
![image](https://user-images.githubusercontent.com/105774467/236153896-94c912cc-67a9-407a-9b8a-c8818124fe51.png)

**Comment by Cryss76** [comment]
The error was caused because tcpdump doesn't have the appropriate permissions to write the results in your analysis folder.
Please reread this part of the docs: https://github.com/cert-ee/cuckoo3/blob/main/docs/src/configuration/system.md#tcpdump
Especially Point 3.1 is most likely to solve that problem.

**Comment by trangnt2304** [comment]
I tried point 3.1 but it does not work

**Comment by trangnt2304** [comment]
hello have anyone solve this :(?

**Comment by Amrith07** [comment]
I am able to run a scan and the analysis is completed. In the terminal log, there is no error being logged. But in the web interface, when I click to see the report, "Server Error (500)" is being thrown. Like mentioned above, I am getting the same error, but just not connected to tcpdump. 
![Screenshot 2023-07-14 104308](https://github.com/cert-ee/cuckoo3/assets/74663418/2494c278-1582-44ca-b6cb-0a9898c3ff9d)

![Screenshot 2023-07-14 104943](https://github.com/cert-ee/cuckoo3/assets/74663418/ea968356-3b59-4c80-b336-e7965633adc7)

**Comment by Amrith07** [comment]
After trying to debug this issue, I found out that, the Internal Error(500), error is due to the routing issue in the Django framework. Adding "/static" to the URL in the above mentioned screenshot, displays the summary web interface of the cuckoo3. Does anyone know what is the reason for this issue ?

**Comment by Amrith07** [comment]
After trying to debug this issue, I found out that, the Internal Error(500), error is due to the routing issue in the Django framework. Adding "/static" to the URL in the above mentioned screenshot, displays the summary web interface of the cuckoo3. Does anyone know what is the reason for this issue ?

**Comment by 3gbCyber** [comment]
Have you fixed the issue? I got the same error

**Comment by Fhwang0926** [comment]
> I got this error when I submit the file to the serrver, it returns "Tasks(s) pending" state with a score of 10 but when I click onto it return a page with an "Server Error (500)". ![image](https://user-images.githubusercontent.com/105774467/236153370-2ca47da1-9188-42df-8359-f61df92eccc0.png) ![image](https://user-images.githubusercontent.com/105774467/236153738-5226e7ed-daa2-422f-81b5-b73b0f607348.png) ![image](https://user-images.githubusercontent.com/105774467/236153896-94c912cc-67a9-407a-9b8a-c8818124fe51.png)

excute cuckoo by root?

**Comment by cert-ee-raidar** [comment]
It is not recommended to run Cuckoo as root user.
You have two issues there. 

1. First disable apparmor profile for tcpdump by running these three commands:
```console
sudo ln -s /etc/apparmor.d/usr.bin.tcpdump /etc/apparmor.d/disable/ && \
sudo apparmor_parser -R /etc/apparmor.d/disable/usr.bin.tcpdump && \
sudo apparmor_parser -r /etc/apparmor.d/usr.bin.tcpdump
```
2. Second problem that gives the 500 error seems te be a missing `resultserver.sock` at `~/.cuckoocwd/operational/sockets/`. Try restarting cuckoo or delete and recreate cuckoocwd

@knowpage Please let us know if the issue is resolved or if these help resolve it.

**Comment by Cryss76** [comment]
The docs only mention to run `sudo apparmor_parser -r /etc/apparmor.d/usr.sbin.tcpdump` so this will be another nice expantion

**Comment by cert-ee-raidar** [comment]
It is covered in the upcoming documentation overhaul and will be done automatically with our new quickstart script

**Comment by cert-ee-raidar** [comment]
Closing the issue due to inactivity
