### ISSUE TITLE
cuckoo.scheduler : no available machines

### ISSUE THREAD

**Issue by Amrith07** [cert-ee/cuckoo3#58]
Sometimes cuckoo fails to run and analyze a file. After some time, the file's status is set to failed. Next when I upload a new file to analyze, cuckoo uploads that file and then in the terminal the cuckoo.sheduler module states that "no available machines". Why is it saying so and how to debug this issue ?
![Screenshot 2023-07-20 122908](https://github.com/cert-ee/cuckoo3/assets/74663418/0fe86e90-8568-4304-95ae-7a03e0d29097)

**Comment by cert-ee-raidar** [comment]
@Amrith07 Did the issue get resolved?
I was not able to reproduce the situation. Do you use single or distributed mode?

**Comment by Cryss76** [comment]
The `No available machines` debug message is issued either when all machines are busy analyzing and tasks are waiting on the queue or when Cuckoo discarded all VMs due to critical errors, resulting in a cuckoo instance with no analysis VMs to use. This is most likely a configuration problem in the VM. I cant tell more because of lacking details about the failed analysis.

**Comment by cert-ee-raidar** [comment]
@Cryss76 comment covers the problem solution.
Closing the issue due to inactivity.
